name: "sa-gpt"
services:
  ## Paperless
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    volumes:
      - paper-data:/usr/src/paperless/data
      - paper-media:/usr/src/paperless/media
      - paper-export:/usr/src/paperless/export
      - paper-consume:/usr/src/paperless/consume
      - sa-content:/usr/src/paperless/media/documents/archive
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
  ##Private GPT
  privategpt:
    ports:
      - "8001:8001"
    image: boxedition/privategpt:gpu-latest
    depends_on:
      - paperless
    volumes:
      - sa-content:/app/local_data/truth
    # Nota
    # Pode ser necessário adicionar make wipe antes to ingest
    entrypoint: /bin/bash -c "make ingest local_data/truth && make run"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

volumes:
  sa-content:
  # Adding default volumes
  redis-data:
  postgres-data:
  paper-data:
  paper-media:
  paper-export:
  paper-consume:
